"""Generate Dart metadata from verified original-model manifest."""
import json
from pathlib import Path
root=Path(__file__).resolve().parents[2]
records=json.loads((root/'web/models/original-v1/manifest.json').read_text())
def dart(value):
 return "'"+value.replace('\\','\\\\').replace("'","\\'").replace('$','\\$').replace('\n','\\n')+"'"
lines=["part of 'presentation_3d_model_catalog.dart';",'', '// Generated by tool/models/generate_catalog.py; keep published variant URLs immutable.', 'const originalPresentation3DModels = <Presentation3DModelAsset>[']
for r in sorted(records,key=lambda r:r['id']):
 v=r['variants']['lite']
 lines += ['  Presentation3DModelAsset(',f"    id: {dart(r['id'])},",f"    label: {dart(r['label'])},",f"    labelEn: {dart(r['labelEn'])},",f"    assetPath: {dart(v['path'])},",f"    qualityAssetPath: {dart(r['variants']['quality']['path'])},",f"    thumbnailPath: {dart(r['thumbnail'])},",f"    category: {dart(r['category'])},",'    tags: <String>['+', '.join(dart(t) for t in r['tags'])+'],',f"    byteSize: {v['bytes']},",f"    sha256: {dart(v['sha256'])},", "    environmentImage: 'neutral',",'    preferBundledAsset: true,','  ),']
lines+= ['];'];(root/'lib/models/original_model_catalog.dart').write_text('\n'.join(lines)+'\n')
print('Generated catalogue:',len(records),'models')
