// Local QA harness only. Dependencies installed outside the application.
const {chromium}=require('/tmp/sutols-model-qa/node_modules/playwright');
const fs=require('fs'),http=require('http'),path=require('path');
const root=process.cwd();
const source=process.argv[2] || 'web/models/anitkabir.glb';
const out=process.argv[3] || 'model-improvements/reports/533a4fd62f2b3444/before';
fs.mkdirSync(out,{recursive:true});
const html=`<!doctype html><html><head><script type="module" src="/viewer.js"></script><style>body{margin:0;background:#e6e9ed}model-viewer{width:960px;height:720px}</style></head><body><model-viewer src="/model.glb" exposure="0.003" environment-image="neutral" shadow-intensity="1" camera-orbit="0deg 65deg auto" interaction-prompt="none"></model-viewer></body></html>`;
const server=http.createServer((q,r)=>{const f=q.url==='/viewer.js'?'/tmp/sutols-model-qa/model-viewer.min.js':q.url==='/model.glb'?path.join(root,source):null;if(f){r.setHeader('Content-Type',q.url.endsWith('.js')?'text/javascript':'model/gltf-binary');fs.createReadStream(f).pipe(r)}else{r.setHeader('Content-Type','text/html');r.end(html)}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--enable-gpu','--use-angle=metal','--disable-background-timer-throttling','--disable-renderer-backgrounding']});try{const context=await browser.newContext({viewport:{width:960,height:720},recordVideo:{dir:out+'/video',size:{width:960,height:720}}});const page=await context.newPage();let errors=[];page.on('pageerror',e=>errors.push(String(e)));await page.goto('http://127.0.0.1:'+server.address().port);await page.waitForFunction(()=>document.querySelector('model-viewer')?.loaded,{timeout:60000});await page.waitForTimeout(1000);await page.evaluate(()=>{let m=document.querySelector('model-viewer');m.play();m.pause();m.currentTime=0});
const baseline=await page.evaluate(()=>{const m=document.querySelector('model-viewer');return {animations:m.availableAnimations,duration:m.duration,dimensions:m.getDimensions(),center:m.getBoundingBoxCenter(),orbit:m.getCameraOrbit(),target:m.getCameraTarget()}});
for(const [name,angle] of [['front',0],['side',90],['three-quarter',45]]){await page.evaluate(a=>{let m=document.querySelector('model-viewer');m.cameraOrbit=`${a}deg 65deg auto`;m.jumpCameraToGoal()},angle);await page.waitForTimeout(300);await page.screenshot({path:out+'/'+name+'.png'});}
await page.evaluate(()=>{let m=document.querySelector('model-viewer');m.play()});await page.waitForTimeout(450);const t1=await page.evaluate(()=>{let m=document.querySelector('model-viewer');m.pause();return m.currentTime});await page.waitForTimeout(300);const t2=await page.evaluate(()=>document.querySelector('model-viewer').currentTime);await page.evaluate(()=>document.querySelector('model-viewer').play());await page.waitForFunction(t=>document.querySelector('model-viewer').currentTime>t, t2,{timeout:15000});const t3=await page.evaluate(()=>{let m=document.querySelector('model-viewer');m.pause();return m.currentTime});
for(const t of [0,1,2,3,4,4.03]){await page.evaluate(t=>document.querySelector('model-viewer').currentTime=Math.min(t,document.querySelector('model-viewer').duration-0.001),t);await page.waitForTimeout(100);await page.screenshot({path:out+'/time-'+t+'.png'});}
await page.evaluate(()=>{const m=document.querySelector('model-viewer');m.minCameraOrbit='auto auto 0m';m.cameraTarget='-48.45m 27m -26m';m.cameraOrbit='0deg 75deg 25m';m.jumpCameraToGoal()});
for(const t of [0,1,2,3,3.98,3.999]){await page.evaluate(t=>document.querySelector('model-viewer').currentTime=t,t);await page.waitForTimeout(160);await page.screenshot({path:out+'/flag-'+t+'.png'});}
await page.evaluate(()=>{const m=document.querySelector('model-viewer');window.qaLoops=[];m.addEventListener('loop',e=>window.qaLoops.push(e.detail));m.currentTime=0;m.play();window.qaPlayback={wraps:0,samples:[]};let previous=0;window.qaTimer=setInterval(()=>{const t=m.currentTime;if(t<previous-0.5)window.qaPlayback.wraps++;window.qaPlayback.samples.push(t);previous=t},50)});await page.waitForFunction(()=>window.qaPlayback.wraps>=3,null,{timeout:30000});await page.evaluate(()=>clearInterval(window.qaTimer));await page.evaluate(()=>document.querySelector('model-viewer').pause());await page.screenshot({path:out+'/flag-three-loops.png'});
fs.writeFileSync(out+'/browser.json',JSON.stringify({...baseline,loopEvents:await page.evaluate(()=>window.qaLoops),playback:await page.evaluate(()=>window.qaPlayback),pauseResume:{t1,t2,t3,pausedStable:t1===t2,resumed:t3>t2},errors,source,renderer:'model-viewer 4.3.1 / Chrome headless Metal requested',viewport:[960,720],realApplicationValidation:'not_run'},null,2));await context.close();console.log(JSON.stringify(baseline));}finally{await browser.close();server.close()}})().catch(e=>{fs.writeFileSync(out+'/browser-failure.json',JSON.stringify({error:String(e),source},null,2));console.error(e);server.close();process.exitCode=1});
